name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Poetry
        run: pip install poetry==2.1.1

      - name: Install dependencies with Poetry
        run: poetry install --with dev

      - name: Run Ruff lint
        run: poetry run ruff check --output-format=github

      - name: Check formatting with Ruff
        run: poetry run ruff format --check

      - name: Check types
        run: |
          poetry run mypy .
